<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    
	<key>fileTypes</key>
	<array>
		<string>u</string>
		<string>uh</string>
		<string>ü</string>
	</array>

	<key>name</key>
	<string>Ü</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*\n</string>
			<key>name</key>
			<string>comment.line.double-dash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![A-Za-z_0-9_])(fn|op|var|auto|return|yield|label|while|loop|break|continue|if|static_if|enable_if|if_coro_advance|else|move|take|byval|tup|struct|class|final|polymorph|interface|abstract|non_sync|ordered|nodiscard|nomangle|call_conv|virtual|override|pure|generator|async|await|namespace|public|private|protected|true|false|mut|imut|constexpr|const|zero_init|this|base|constructor|destructor|conversion_constructor|static_assert|halt|safe|type|typeinfo|same_type|typeof|template|enum|cast_ref|cast_imut|alloca|as|is|import|export|embed|default|delete|for|with|do|switch|case|typename|lambda|static|package|module|mixin|thread_local)(?![A-Za-z_0-9_])</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
	</array>

	<key>repository</key>
	<dict>
	</dict>

	<key>scopeName</key>
	<string>source.u</string>

	<key>uuid</key>
	<string>958518BC-799F-477A-99F9-5B28EBF230F6</string>
</dict>
</plist>
