// Keywords list.
// Usage - define macro PROCESS_KEYWORD, include this file, undefune macro PROCESS_KEYWORD.

// Common keywords.
PROCESS_KEYWORD( fn )
PROCESS_KEYWORD( op )
PROCESS_KEYWORD( var )
PROCESS_KEYWORD( auto )
PROCESS_KEYWORD( lock_temps )
PROCESS_KEYWORD( return )
PROCESS_KEYWORD( while )
PROCESS_KEYWORD( break )
PROCESS_KEYWORD( continue )
PROCESS_KEYWORD( if )
PROCESS_KEYWORD( static_if )
PROCESS_KEYWORD( enable_if )
PROCESS_KEYWORD( else )
PROCESS_KEYWORD( move )
PROCESS_KEYWORD( select )

PROCESS_KEYWORD( tup )
PROCESS_KEYWORD( struct )
PROCESS_KEYWORD( class )
PROCESS_KEYWORD( final )
PROCESS_KEYWORD( polymorph )
PROCESS_KEYWORD( interface )
PROCESS_KEYWORD( abstract )
PROCESS_KEYWORD( shared )
PROCESS_KEYWORD( ordered )

PROCESS_KEYWORD( nomangle )
PROCESS_KEYWORD( virtual )
PROCESS_KEYWORD( override )
PROCESS_KEYWORD( pure )

PROCESS_KEYWORD( namespace )

PROCESS_KEYWORD( public )
PROCESS_KEYWORD( private )
PROCESS_KEYWORD( protected )

// Fundamental types names.
PROCESS_KEYWORD( void )
PROCESS_KEYWORD( bool )
PROCESS_KEYWORD( i8  )
PROCESS_KEYWORD( u8  )
PROCESS_KEYWORD( i16 )
PROCESS_KEYWORD( u16 )
PROCESS_KEYWORD( i32 )
PROCESS_KEYWORD( u32 )
PROCESS_KEYWORD( i64 )
PROCESS_KEYWORD( u64 )
PROCESS_KEYWORD( i128 )
PROCESS_KEYWORD( u128 )
PROCESS_KEYWORD( f32 )
PROCESS_KEYWORD( f64 )
PROCESS_KEYWORD( char8 )
PROCESS_KEYWORD( char16 )
PROCESS_KEYWORD( char32 )
PROCESS_KEYWORD( size_type )

// Boolean constants.
PROCESS_KEYWORD( true )
PROCESS_KEYWORD( false )

// Mutability modifiers.
PROCESS_KEYWORD( mut )
PROCESS_KEYWORD( imut )
PROCESS_KEYWORD( constexpr )

PROCESS_KEYWORD( zero_init )
PROCESS_KEYWORD( uninitialized )

PROCESS_KEYWORD( this )
PROCESS_KEYWORD( base )
PROCESS_KEYWORD( constructor )
PROCESS_KEYWORD( destructor )
PROCESS_KEYWORD( conversion_constructor )

PROCESS_KEYWORD( static_assert )
PROCESS_KEYWORD( halt )
PROCESS_KEYWORD( safe )
PROCESS_KEYWORD( unsafe )

PROCESS_KEYWORD( type )
PROCESS_KEYWORD( typeinfo )
PROCESS_KEYWORD( typeof )
PROCESS_KEYWORD( template )
PROCESS_KEYWORD( enum )

PROCESS_KEYWORD( cast_ref )
PROCESS_KEYWORD( cast_ref_unsafe )
PROCESS_KEYWORD( cast_imut )
PROCESS_KEYWORD( cast_mut )

PROCESS_KEYWORD( import )

PROCESS_KEYWORD( default )
PROCESS_KEYWORD( delete )

// Reserved keywords for future usage.
PROCESS_KEYWORD( for )
PROCESS_KEYWORD( do )
PROCESS_KEYWORD( switch )
PROCESS_KEYWORD( case )
PROCESS_KEYWORD( typename )
PROCESS_KEYWORD( const )
PROCESS_KEYWORD( lambda )
PROCESS_KEYWORD( static )
PROCESS_KEYWORD( package )
PROCESS_KEYWORD( module )
PROCESS_KEYWORD( export )

PROCESS_KEYWORD( i256 )
PROCESS_KEYWORD( u256 )
PROCESS_KEYWORD( i512 )
PROCESS_KEYWORD( u512 )
PROCESS_KEYWORD( i1024 )
PROCESS_KEYWORD( u1024 )
PROCESS_KEYWORD( i2048 )
PROCESS_KEYWORD( u2048 )
PROCESS_KEYWORD( i4096 )
PROCESS_KEYWORD( u4096 )
