#include <cassert>
#include <iostream>

// These symbols should be generated by Ü compiler.
extern "C" const char __U_sprache_compiler_version[];
extern "C" const int __U_sprache_compiler_generation;

// Custom halt handler should be available.
extern "C" void (*_U_halt_handler)();

static void TestHaltHandler(){}

int main()
{
	_U_halt_handler= TestHaltHandler;
	assert( __U_sprache_compiler_generation >= 0 );
	std::cout << "Compiler version: " << __U_sprache_compiler_version << ", generation: " << __U_sprache_compiler_generation << std::endl;
}
