name: FreeBSD build

on: [push]

jobs:
  build_freebsd_release_llvm_src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build FreeBSD release LLVM src
        uses: cross-platform-actions/action@v0.26.0
        with:
          operating_system: freebsd
          version: '14.2'
          run: cd /home/runner/work/U-00DC-Sprache/U-00DC-Sprache && pkg install clang cmake gcc git wget && sh ./ci/build_release_freebsd_llvm_src.sh
