name: CI

on: [push]

jobs:
  build_release_llvm_bin:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build project
      run: |
        sudo apt-get install ninja-build sphinx-doc sphinx-common python-stemmer
        ./ci/build_release_llvm_bin.sh
    - uses: actions/upload-artifact@v3
      with:
        name: compiler artifacts
        path: install/
