name: CI

on: [push]

jobs:
  gnu_linux_x86_64_release_llvm_bin:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: build project
      run: |
        sudo apt-get update && sudo apt-get install ninja-build python3-sphinx sphinx-doc sphinx-common python3-stemmer
        ./ci/build_gnu_linux_x86_64_release_llvm_bin.sh
    - uses: actions/upload-artifact@v4
      with:
        name: compiler_gnu_linux
        path: install/
