name: WindowsBuild

on: [workflow_dispatch]

jobs:
  build_windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: build project
      run: ./ci/build_release_windows.ps1
    - uses: actions/upload-artifact@v3
      with:
        name: compiler_windows
        path: install/
